// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitled', function() {
  this.timeout(70000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
  //  await driver.quit();
  })
  it('Untitled', async function() {
    await driver.get("https://amazonairpro.com/")
    await driver.sleep(2000)
    await driver.manage().window().setRect(1031, 953)
    await driver.findElement(By.linkText("ABOUT US")).click()
    const actions = driver.actions({bridge: true});
    var elem=await driver.findElement(By.id("menu-item-20"));
    await actions.move({duration:5000,origin:elem,x:0,y:0}).perform();
    await driver.findElement(By.xpath("//li[@id=\'menu-item-101\']/a")).click()
  })
})
